spring:
  application:
    name: taverna-sorte-backend

  datasource:
    url: jdbc:mysql://localhost:3307/taverna_sorte
    username: taverna
    password: taverna123

  jpa:
    hibernate:
      ddl-auto: update
